Repository PolyMathOrg/PolyMath, pull requests merged in 2019-05, with the labels that each got.

#119 Issue 29 - PMVector/PMMatrix >> #dot: does not compute a dot product.
  src/Math-Core/PMVector.class.st
  src/Math-Core/PMWeightedPoint.class.st
  src/Math-Matrix/PMJacobiTransformationHelper.class.st
  src/Math-Matrix/PMLUPDecomposition.class.st
  src/Math-Matrix/PMLargestEigenValueFinder.class.st
  src/Math-Matrix/PMLinearEquationSystem.class.st
  src/Math-Matrix/PMMatrix.class.st
  src/Math-Matrix/PMSingularMatrixError.class.st
  src/Math-Matrix/PMSingularValueDecomposition.class.st
  src/Math-Matrix/PMSymmetricMatrix.class.st
  src/Math-PrincipalComponentAnalysis/PMSciKitLearnSVDFlipAlgorithm.class.st
  src/Math-Tests-Core/PMVectorTest.class.st
  src/Math-Tests-Matrix/PMAdditionalTest.class.st
  src/Math-Tests-Matrix/PMMatrixTest.class.st
  src/Math-Tests-Matrix/PMQRTest.class.st
  src/Math-Tests-Matrix/PMRestTest.class.st
  src/Math-Tests-Matrix/PMSingularValueDecompositionTest.class.st
  src/Math-Tests-Matrix/PMSymmetricMatrixTest.class.st
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#126 Removed PMVector sum for speedup
  src/Math-Core/PMVector.class.st
  src/Math-Core/PMWeightedPoint.class.st
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#117 Implementing the t-SNE algorithm
  src/Math-TSNE/PMTSNE.class.st
  src/Math-Tests-TSNE/PMTSNETest.class.st
Labels: Priority: Medium, Status: In Progress, Type: Enhancement
